using System;
using System.Linq;
using QuestPDF.Elements.Text;
using QuestPDF.Elements.Text.Items;
using QuestPDF.Infrastructure;
using QuestPDF.Skia;

namespace QuestPDF.Helpers
{
    /// <summary>
    /// Provides high-level abstractions for measuring text layout metrics within the QuestPDF ecosystem.
    /// </summary>
    public static class TextLayoutMeasurer
    {
        /// <summary>
        /// Calculates the vertical height of text content considering container constraints and internal spacing.
        /// </summary>
        /// <param name="text">The string content to measure.</param>
        /// <param name="style">The typography configuration.</param>
        /// <param name="maxWidth">The total width of the parent container.</param>
        /// <param name="paddingLeft">Left internal spacing to subtract from available width.</param>
        /// <param name="paddingRight">Right internal spacing to subtract from available width.</param>
        /// <returns>The total height required to render all lines of text.</returns>
        public static float GetHeight(
            string text,
            TextStyle style,
            float maxWidth,
            float paddingLeft = 0f,
            float paddingRight = 0f)
        {
            var metrics = Measure(text, style, maxWidth, paddingLeft, paddingRight);
            return metrics?.Sum(line => line.Height) ?? 0f;
        }

        /// <summary>
        /// Determines the total line count after text wrapping logic is applied within the given constraints.
        /// </summary>
        /// <param name="text">The string content to measure.</param>
        /// <param name="style">The typography configuration.</param>
        /// <param name="maxWidth">The total width of the parent container.</param>
        /// <param name="paddingLeft">Left internal spacing to subtract from available width.</param>
        /// <param name="paddingRight">Right internal spacing to subtract from available width.</param>
        /// <returns>The number of lines generated by the layout engine.</returns>
        public static int GetLineCount(
            string text,
            TextStyle style,
            float maxWidth,
            float paddingLeft = 0f,
            float paddingRight = 0f)
        {
            var metrics = Measure(text, style, maxWidth, paddingLeft, paddingRight);
            return metrics?.Length ?? 0;
        }

        /// <summary>
        /// Internal core engine that executes the QuestPDF measurement process.
        /// </summary>
        private static SkSize[]? Measure(
            string text,
            TextStyle style,
            float maxWidth,
            float paddingLeft,
            float paddingRight)
        {
            if (string.IsNullOrWhiteSpace(text))
                return null;

            // Calculate Effective Width: Content Boundary = Total Width - Horizontal Offsets
            var effectiveWidth = Math.Max(0, maxWidth - (paddingLeft + paddingRight));
            if (effectiveWidth <= 0)
                return null;

            using var textBlock = new TextBlock
            {
                Items =
                [
                    new TextBlockSpan
                    {
                        Text = text,
                        Style = style ?? TextStyle.Default
                    }
                ]
            };

            textBlock.Measure(new Size(effectiveWidth, float.MaxValue));
            return textBlock.LineMetrics;
        }
    }
}